services:
  postgres:
    image: postgres:15
    container_name: mlflow-postgres
    networks:
      - shared-net
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    networks:
      - shared-net
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow@postgres:5432/mlflow
      MLFLOW_DEFAULT_ARTIFACT_ROOT: s3://pipeout-database/mlflow-artifacts
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    command:
      [
        "mlflow",
        "server",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--allowed-hosts",
        "mlflow, mlflow:5000,localhost:5000, 0.0.0.0:5000",
      ]
volumes:
  postgres_data:

networks:
  shared-net:
    name: ml-network
    driver: bridge
